### PR TITLE
uncommented out line in json example that used to crash the Swift compiler

### PR DESCRIPTION
**Pull request by jpsim**
This just works with Xcode 8 beta 6, so I just uncommented it.

### CODE REVIEW

**Comment by behrang** [comment]
With latest Swift toolchain (swift-3.0-PREVIEW-6) with `swift build` it compiles. But when I run the example with `.build/debug/example-json example-json/movies.json` I get `Segmentation fault: 11`.

Can you test it on the command line too?

**Comment by jpsim** [comment]
Ah, I see what's happening. There's infinite recursion because of the circular dependency between `value()` and `array()`. They both invoke each other.

I don't suppose there's an easy fix for this...

By the way, I find it easier to debug with Xcode, which graphically indicated to me via lldb that this is what was happening. You can use the Swift Package Manager to generate an Xcode project: `swift package generate-xcodeproj`.

**Comment by behrang** [comment]
Ah! Great. Thank you.

I'm working on it.

**Comment by behrang** [comment]
Many thanks. Changed many things and bumped major version. It is now working as expected but API is changed a little.

**Comment by jpsim** [comment]
Thanks!

**Pull request closed without merging**
